name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: circleci/clojure:lein-2.7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: lein do clean, cljsbuild once electron-dev, cljsbuild once frontend-dev, clean, cljsbuild once electron-release, cljsbuild once frontend-release
      env:
        LEIN_ROOT: nbd
        JVM_OPTS: -Xmx3200m
